### ISSUE TITLE
why discontinued?

### ISSUE THREAD

**Issue by c2c2** [prijindal/kuzzle_dart#11]
Hi, as you know firebase is only platform that support flutter but firebase will be too expensive in grow. Will you continue this library or finished?

**Comment by prijindal** [comment]
I don't want to call it discontinued.
It is just that I am currently not able to provide enough time on this, that's all.
But i am open to review and accept any pull request, fix any bugs.
or if @stafyniaksacha is willing to mantain this in the long term, i can give him that access

**Comment by stafyniaksacha** [comment]
@prijindal, yes if you need, I can help maintain this project (I'm an old member of kuzzle' core team)
I'm also planing to work on this project again to introduce some new features that are already implemented into the new javascript SDK.
Don't hesitate to ask questions about kuzzle , the sdk, or even request for features !

**Comment by Aschen** [comment]
@c2c2 Concerning this SDK we (the Kuzzle team) can not provide the same level of support than for our official project. 
But as @stafyniaksacha says, he is an old member of our team and we trust him to provide the best quality support for this SDK.

Concerning the backend core (http://github.com/kuzzleio/kuzzle) is a long term project. We have a LTS development cycle, every version of Kuzzle is supported for at least 18 month.  
Kuzzle is a free and open source software but a company is behind it and we have a lot of clients who pay for support so even if I can not say that Kuzzle will last forever, it will stay for a while I think ;)

**Comment by c2c2** [comment]
Thanks for your responsibility but i ran an startup with dead time and i think maybe another project i'll use kuzzle for backend

**Comment by stafyniaksacha** [comment]
@c2c2 You are starting a new project using Flutter ?

**Comment by c2c2** [comment]
Yes i do

**Comment by stafyniaksacha** [comment]
@c2c2 What are missing for your project ? Normally all functionalities are implemented as javascript sdk v6.0.0. 

Don't hesitate to ask for questions about implementation with flutter here, I'll be happy to help you!
You may find support for global kuzzle usage on the official gitter chat here: https://gitter.im/kuzzleio/kuzzle

I saw that there are plan to officially do support for this sdk on official roadmap here: https://trello.com/c/b28UCNX3/41-official-dart-flutter-sdk
