### ISSUE TITLE
Version 2 support

### ISSUE THREAD

**Issue by sasha-polev** [prijindal/kuzzle_dart#13]
Although most functionality seem to work out of the box (except for breaking changes I guess), the check for version kills it at the start.

Removing setting request.volatile['sdkVersion'] does make it somewhat usable. 

It should be possible to create version for 2.0 with limited functionality without much changes, I guess.

**Comment by Manuelbaun** [comment]
@sasha-polev, I started on that. A pull request exists now.

**Comment by prijindal** [comment]
@Manuelbaun pull request have been reviewed, merged and pushed to pub.
Thanks a lot for your contribution

**Comment by prijindal** [comment]
#14
